
POST http://localhost:3000/createtoken
Content-Type: application/json

{
    "data":{
        "email": "cs@cs.com",
        "pass": "asdas"
    }
}

###

POST http://localhost:3000/updateUserPass
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDM5QHVuaXdhLmdyIiwiaWF0IjoxNjMzODI1NzM2LCJleHAiOjE2MzM4MjU3NjF9.Gy6yw100WFKLSqv4IePmL5EeMo5FDgE52KFp5F0rPLg

{
    "data":{
        "email": "cs141039@uniwa.gr",
        "pass": "12345"
    }
}

###

POST  http://localhost:3000/register
Content-Type: application/json

{
    "data":{
        "email": "cs@cs.com",
        "password": "12345",
        "mobile": "12313",
        "fullname": "lefos evan",
        "gender": "male",
        "car": "toyota",
        "cardate": "1996",
        "age": "26",
        "photo": "12131231"
    }
}

###

POST http://localhost:3000/verify
Content-Type: application/json

{
    "data":{
        "email": "cs@cs.com"
    }
}

###
POST http://localhost:3000/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzQGNzLmNvbSIsImlhdCI6MTYzMzk4ODkyMywiZXhwIjoxNjM5MTcyOTIzfQ.5iJ7P5dgY6AwMv06E0d2Cy6FAdRGP24lRMvf_aiXCAw

{
    "data":{
        "email": "lefterisevagelinos1996@gmail.com",
        "pass": "12345"
    }
}

###

POST http://localhost:3000/passotp
Content-Type: application/json

{
    "data": {
        "email": "cs@cs.com"
    }
}

###

POST http://localhost:3000/createpost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDM5QHVuaXdhLmdyIiwiaWF0IjoxNjMzOTA0Mzc3LCJleHAiOjE2MzkwODgzNzd9.gca_86jwWOpVujOSo25W1DOz2A0wXZ7JgbrkWOhqCSA

{
    "data": {
        "email": "cs141039@uniwa.gr",
        "startplace": "volos",
        "endplace": "Athens",
        "numseats": "3",
        "startdate": "2021-11-25",
        "enddate": "2021-11-26",
        "costperseat": "20",
        "comment": "Αν δεν επικοινωνήσω σημαίνει ότι δεν υπάρχουν θέσεις.",
        "moreplaces": {
            "places": "Larisa-Trikala-Lamia"
        }
    }
}

###

POST http://localhost:3000/interested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDM5QHVuaXdhLmdyIiwiaWF0IjoxNjMzOTA0Mzc3LCJleHAiOjE2MzkwODgzNzd9.gca_86jwWOpVujOSo25W1DOz2A0wXZ7JgbrkWOhqCSA

{
    "data": {
        "postid": "9",
        "email": "lefterisevagelinos1996@gmail.com"
    }
}