#service poy ftiaxnei token ston xrhsth, enw an den einai verified stelnei email ston xrhsth kai to otp ston client gia epivevaiwsh
POST http://localhost:3000/createtoken
Content-Type: application/json

{
    "data":{
        "email": "user0@gmail.com"
    }
}

###

#service pou kanei update to password you user sth vash
POST http://localhost:3000/updateUserPass
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4


{
    "data":{
        "email": "cs141082@uniwa.gr",
        "pass": "12356"
    }
}

###

#service poy kanei register ton xrhsth sth vash kai stelnei amesws otp gia epivevaish tou email
POST  http://localhost:3000/register
Content-Type: application/json

{
    "data":{
        "email": "lefterisevagelinos1996@gmail.com",
        "password": "12345",
        "mobile": "6975620785",
        "fullname": "lefos evan",
        "gender": "male",
        "car": "toyota",
        "cardate": "1996",
        "age": "26",
        "photo": ""
    }
}

###

#service pou kanei verify to xrhsth sth vash dedomenwn, afou kanei epibebaiwsh to otp tou ston client
POST http://localhost:3000/verify
Content-Type: application/json

{
    "data":{
        "email": "lefterisevagelinos1996@gmail.com"
    }
}

###

#service pou elegxei ta stoixeia tou xrhsth otan kanei login
POST http://localhost:3000/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data":{
        "email": "user0@gmail.com",
        "pass": "12356"
    }
}

###

#service poy stelnei otp ston xrhsth kai ston client gia epibebaiwsh
POST http://localhost:3000/passotp
Content-Type: application/json

{
    "data": {
        "email": "cs141082@uniwa.gr"
    }
}

###

#service pou ftiaxneis ena post
POST http://localhost:3000/createpost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAzVDE2OjA0OjAyLjE5MFoiLCJpYXQiOjE2NDYzMjM0NDIsImV4cCI6MTY1MTUwNzQ0Mn0.lx4Z5sj9VopjkLQuJp_xjkey-hY23dInagKmv9oh1VU

{
    "data": {
        "email": "user0@gmail.com",
        "date": "2021-10-05",
        "startplace": "ασδ",
        "startcoord": "123",
        "endplace": "δσα",
        "endcoord": "321",
        "numseats": 2,
        "startdate": "2022-12-22",
        "enddate": "2022-12-22",
        "returnStartDate": "2022-12-20",
        "returnEndDate": "2022-12-21",
        "withReturn": true,
        "costperseat": 40,
        "comment": "Αν δεν επικοινωνήσω σημαίνει ότι δεν υπάρχουν θέσεις.",
        "petAllowed": true,
        "moreplaces": [
            {
                    "place": "lamia",
                    "placecoords": "123"
            },
            {
                    "place": "lamia",
                    "placecoords": "123"
            }
        ]
    }
}

###

#service poy kaleis gia na deiksei kapoios endiaferon gia ena post
POST http://localhost:3000/interested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data": {
        "email": "lefterisevagelinos1996@gmail.com",
        "postid": 1155
    }
}

###

#service pou sou epistrefei lista me posts (paginated ana 20 kai ordered me vasi imeromhnia)
POST http://localhost:3000/searchposts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data": {
        "email": "lefterisevagelinos1996@gmail.com",
        "startplace": "Volos",
        "startcoord": "123",
        "endplace": "Athens",
        "endcoord": "1",
        "startdate": "2021-10-05",
        "enddate": "2022-12-19",
        "page": 1,
        "cost": 100,
        "age": null,
        "age_end": null,
        "car": null,
        "cardate": null,
        "gender": null,
        "withReturn": true,
        "petAllowed": true,
        "returnStartDate": "2022-12-19",
        "returnEndDate": "2022-12-20"
    }
}

# {
#     "data": {
#         "email": "lefterisevagelinos1996@gmail.com",
#         "startplace": "Volos",
#         "startcoord": "123",
#         "endplace": "Athens",
#         "endcoord": "1",
#         "startdate": "2021-10-14",
#         "enddate": "2021-12-20",
#         "page": 1,
#         "cost": 1,
#         "age": null,
#         "age_end": null,
#         "car": null,
#         "cardate": null,
#         "gender": "male"
#     }
# }



###

#service pou anazhtei kapoion xrhsth kai epistrefei ta stoixeia toy
POST http://localhost:3000/searchuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTI2VDE1OjQ5OjQwLjI4OFoiLCJpYXQiOjE2NDU4OTA1ODAsImV4cCI6MTY1MTA3NDU4MH0.RVDRHuPubDnW-W8kXAEhpV77cppmfMdSYbwMPPeCWvU

{
    "data": {
        "email": "user0@gmail.com"
    }
}

###

#get reviews
POST http://localhost:3000/getReviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data": {
        "email": "lefterisevagelinos1996@gmail.com",
        "page": 1
    }
}

###

#Service pou eisagei ena review sth vash
POST http://localhost:3000/createreview
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTI2VDE1OjQ5OjQwLjI4OFoiLCJpYXQiOjE2NDU4OTA1ODAsImV4cCI6MTY1MTA3NDU4MH0.RVDRHuPubDnW-W8kXAEhpV77cppmfMdSYbwMPPeCWvU

{
    "data": {
        "email": "lefterisevagelinos1996@gmail.com",
        "emailreviewer": "user0@gmail.com",
        "rating": 4,
        "text": "Πολύ καλός οδηγός, αλλά μιλάει συνέχεια test"
    }
}

###

#service epistrefei lista me posts enos xrhsth
POST http://localhost:3000/getPostsUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAyVDEzOjA0OjUwLjEyOVoiLCJpYXQiOjE2NDYyMjYyOTAsImV4cCI6MTY1MTQxMDI5MH0.H1G6LpsVxZoglMmCRbcPFdinQ4Na2_-80C3N68nvDgg

{
    "data": {
        "email": "user0@gmail.com",
        "page": 1
    }
}
###

//Διαγρφή post μαζί με τους ενδιαφερόμενους του post
POST http://localhost:3000/deletePost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data": {
        "postid": 1565
    }
}
###

//delete of interested
POST http://localhost:3000/deleteInterested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data": {
        "piid": 114
    }
}

###

#service poy epistrefei ta post gia ta opoia einai interested o user
POST http://localhost:3000/getInterestedPerUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data": {
        "email": "lefterisevagelinos1996@gmail.com"
    }
}

###

#service epistrefei lista me endiaferomenous gia ta posts enos user
POST http://localhost:3000/getInterested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTAxVDEyOjE1OjQ4LjUwM1oiLCJpYXQiOjE2NDM3MTc3NDgsImV4cCI6MTY0ODkwMTc0OH0.3hGmuEdGzpdhiny9YD5qIAoiD8I-TPDVHcEyH1VG3FY

{
    "data": {
        "email": "user0@gmail.com",
        "page": 1
    }
}
###

#service epistrefei lista me endiaferomenous gia ena post
POST http://localhost:3000/getIntPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data": {
        "postid": 1721,
        "page": 1
    }
}
###

GET http://localhost:3000/autocomplete/json?input=αθη
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTE5VDE3OjE3OjIwLjA0NVoiLCJpYXQiOjE2NDUyOTEwNDAsImV4cCI6MTY1MDQ3NTA0MH0.OVf2DDS4hIeyPV3PJNbZG56iKL8-rkVtVSMzUQ3rdLI

###
GET http://localhost:3000/details/json?place_id=ChIJ8UNwBh-9oRQR3Y1mdkU1Nic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTE5VDE3OjE3OjIwLjA0NVoiLCJpYXQiOjE2NDUyOTEwNDAsImV4cCI6MTY1MDQ3NTA0MH0.OVf2DDS4hIeyPV3PJNbZG56iKL8-rkVtVSMzUQ3rdLI

###
// verify an insterested user to a post
POST http://localhost:3000/verInterested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTE5VDE3OjE3OjIwLjA0NVoiLCJpYXQiOjE2NDUyOTEwNDAsImV4cCI6MTY1MDQ3NTA0MH0.OVf2DDS4hIeyPV3PJNbZG56iKL8-rkVtVSMzUQ3rdLI

{
    "data": {
        "postid": 1155,
        "piid": 57
    }
}

###

//service to notify someone that has been verified for a post that he is interested
POST http://localhost:3000/notifyMe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTAxVDEyOjE1OjQ4LjUwM1oiLCJpYXQiOjE2NDM3MTc3NDgsImV4cCI6MTY0ODkwMTc0OH0.3hGmuEdGzpdhiny9YD5qIAoiD8I-TPDVHcEyH1VG3FY

###
// mainEmail: se afto to email tha ginontai generated ta posts. 
// Epishs to idio email tha einai to pathitiko eimail twn reviews. (dhladh se afton tha kanoyn to review)
// To secondaryEmail einai o emailReviewer dhladh aftow poy tha kanei to review
// Gia na treksei duo fores h perissoteres to api prepei na allazei kathe fora to secondary email. (Den einai aparaithto na einai uparkto email)
// postid: dineis to id apo to post sto opoio thes na ginoun generated polloi endiaferomenoi
// postidList: lista me postid poy thes enas user na endiaferetai gia afta
POST http://localhost:3000/dbMigration
Content-Type: application/json

{
    "data": {
        "mainEmail": "lefterisevagelinos1996@gmail.com",
        "secondaryEmail": "cs1410823@uniwa.gr",
        "postid": 849,
        "postidList": [1564,1565,1566,1567,1568]
    }
}

###
POST http://localhost:3000/sendReport
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTAxVDEyOjE1OjQ4LjUwM1oiLCJpYXQiOjE2NDM3MTc3NDgsImV4cCI6MTY0ODkwMTc0OH0.3hGmuEdGzpdhiny9YD5qIAoiD8I-TPDVHcEyH1VG3FY

{
    "text": "Test report"
}
###

POST http://localhost:3000/getTerms
Content-Type: application/text/html
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTAxVDEyOjE1OjQ4LjUwM1oiLCJpYXQiOjE2NDM3MTc3NDgsImV4cCI6MTY0ODkwMTc0OH0.3hGmuEdGzpdhiny9YD5qIAoiD8I-TPDVHcEyH1VG3FY
###

POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=---

###

POST http://localhost:3000/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAyVDEzOjA0OjUwLjEyOVoiLCJpYXQiOjE2NDYyMjYyOTAsImV4cCI6MTY1MTQxMDI5MH0.H1G6LpsVxZoglMmCRbcPFdinQ4Na2_-80C3N68nvDgg

{
    "data": {
        "mobile": "6975620785",
        "age": 25,
        "facebook": null,
        "instagram": null,
        "car": "nissan",
        "cardate": "1996"
    }
}

###

POST http://localhost:3000/createRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAyVDEzOjA0OjUwLjEyOVoiLCJpYXQiOjE2NDYyMjYyOTAsImV4cCI6MTY1MTQxMDI5MH0.H1G6LpsVxZoglMmCRbcPFdinQ4Na2_-80C3N68nvDgg

{
    "data": {
        "startplace": "Volos",
        "startcoord": "123",
        "endplace": "Athens",
        "endcoord": "321",
        "startdate": "2022-12-20",
        "enddate": "2022-12-22"
    }
}

###

POST http://localhost:3000/getRequests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAyVDEzOjA0OjUwLjEyOVoiLCJpYXQiOjE2NDYyMjYyOTAsImV4cCI6MTY1MTQxMDI5MH0.H1G6LpsVxZoglMmCRbcPFdinQ4Na2_-80C3N68nvDgg

###
POST http://localhost:3000/deleteRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAyVDEzOjA0OjUwLjEyOVoiLCJpYXQiOjE2NDYyMjYyOTAsImV4cCI6MTY1MTQxMDI5MH0.H1G6LpsVxZoglMmCRbcPFdinQ4Na2_-80C3N68nvDgg

{
    "data": {
        "postSearchId": 6
    }
}