#service poy ftiaxnei token ston xrhsth, enw an den einai verified stelnei email ston xrhsth kai to otp ston client gia epivevaiwsh
POST http://localhost:3000/users/createtoken
Content-Type: application/json

{
    "data":{
        "email": "user0@gmail.com"
    }
}

###

#service pou kanei update to password you user sth vash
POST http://localhost:3000/updateUserPass
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTEwLTI2VDE0OjU3OjI4LjI5MVoiLCJpYXQiOjE2NjY3OTYyNDgsImV4cCI6MTY3MTk4MDI0OH0.aqDYU4dG3OfcVJ39eiLxiAAqU2y8V8-A_1dLpfDq2EA

{
    "data":{
        "email": "lefterisevagelinos1996@gmail.com",
        "pass": "11111"
    }
}

###
POST http://localhost:3000/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTA0LTIxVDA5OjMwOjIwLjA5NloiLCJpYXQiOjE2NTA1MzM0MjAsImV4cCI6MTY1NTcxNzQyMH0.3cTeMd_dQ-yQFpf0DLaA3d_foLF7cd8bDo3JbRGN93M


{
    "data": {
        "fullname": "George",
        "mobile": "6975620785",
        "age": 25,
        "facebook": null,
        "instagram": null,
        "car": "nissan",
        "cardate": "1996",
        "photo": "/9j/4AAQSkZJRgABAQEAeAB4AAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAYACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKKKACiiigAooooAKKKKACiiigAooooA//Z"
    }
}

###

#service poy kanei register ton xrhsth sth vash kai stelnei amesws otp gia epivevaish tou email
POST  http://localhost:3000/register
Content-Type: application/json

{
    "data":{
        "email": "lefterisevagelinos1996@gmail.com",
        "password": "12345",
        "mobile": "6975620785",
        "fullname": "lefos evan",
        "gender": "male",
        "car": null,
        "cardate": null,
        "age": "26",
        "photo": "/9j/4AAQSkZJRgABAQEAeAB4AAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAYACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKKKACiiigAooooAKKKKACiiigAooooA//Z"
    }
}

###

#service pou kanei verify to xrhsth sth vash dedomenwn, afou kanei epibebaiwsh to otp tou ston client
POST http://localhost:3000/users/verify
Content-Type: application/json

{
    "data":{
        "email": "lefterisevagelinos1996@gmail.com"
    }
}

###

#service pou elegxei ta stoixeia tou xrhsth otan kanei login
POST http://localhost:3000/users/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlZnRlcmlzZXZhZ2VsaW5vczE5OTZAZ21haWwuY29tIiwiZGF0YSI6IjIwMjItMTEtMDhUMTk6MzY6MDcuMDIyWiIsImlhdCI6MTY2NzkzNjE2NywiZXhwIjoxNjczMTIwMTY3fQ.Rm7X-PLNZBFnmAEssYrXCJr1Mxv_KxnoGa0ojWbfG_E

{
    "data":{
        "email": "lefterisevagelinos1996@gmail.com",
        "pass": "11111"
    }
}

###

#service poy stelnei otp ston xrhsth kai ston client gia epibebaiwsh
POST http://localhost:3000/users/passotp
Content-Type: application/json

{
    "data": {
        "email": "lefterisevagelinos1996@gmail.com"
    }
}

###

POST http://localhost:3000/setVisible
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTMxVDA5OjAwOjI3LjQ5NloiLCJpYXQiOjE2NDg3MTcyMjcsImV4cCI6MTY1MzkwMTIyN30.kkSrxOTXM7gPgORYf_AE4Q50cOR_OZ0Lk8cIUgn1eho

###

#service pou ftiaxneis ena post
POST http://localhost:3000/createpost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlZnRlcmlzZXZhZ2VsaW5vczE5OTZAZ21haWwuY29tIiwiZGF0YSI6IjIwMjItMDYtMTdUMTI6NTY6MDAuMzkwWiIsImlhdCI6MTY1NTQ3MDU2MCwiZXhwIjoxNjYwNjU0NTYwfQ.rc3qgCqziUl3FkhTb7SDfH95TZrbyICS50nxj1DOahQ

{
    "data": {
        "email": "user0@gmail.com",
        "date": "2021-10-05",
        "startplace": "ασδ",
        "startcoord": "1234",
        "endplace": "δσα",
        "endcoord": "3215",
        "numseats": 2,
        "startdate": "2022-04-22",
        "enddate": null,
        "returnStartDate": null,
        "returnEndDate": null,
        "withReturn": false,
        "costperseat": 40,
        "comment": "Αν δεν επικοινωνήσω σημαίνει ότι δεν υπάρχουν θέσεις.",
        "petAllowed": true,
        "isFavourite": false,
        "moreplaces": [
            {
                    "place": "lamia",
                    "placecoords": "3211"
            },
            {
                    "place": "lamia",
                    "placecoords": "3211"
            }
        ]
    }
}
###

#service pou ftiaxneis ena post
POST http://localhost:3000/createpost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTA2LTI2VDE2OjUyOjIzLjIyOFoiLCJpYXQiOjE2NTYyNjIzNDMsImV4cCI6MTY2MTQ0NjM0M30._PWmI7NvBmjRG3cPF0-fPJLQw0-gDbmkuMclk5HD57U

{
    "data": {
        "email": "user1@gmail.com",
        "date": "2022-06-26",
        "startplace": "Βόλος",
        "startcoord": "1234",
        "endplace": "Αθήνα",
        "endcoord": "3215",
        "numseats": 2,
        "startdate": "2022-04-22",
        "enddate": "2022-04-21",
        "returnStartDate": "2022-12-20",
        "returnEndDate": "2022-12-21",
        "withReturn": true,
        "costperseat": 40,
        "comment": "Αν δεν επικοινωνήσω σημαίνει ότι δεν υπάρχουν θέσεις.",
        "petAllowed": true,
        "isFavourite": false,
        "moreplaces": [
            {
                    "place": "lamia",
                    "placecoords": "3211"
            },
            {
                    "place": "lamia",
                    "placecoords": "3211"
            }
        ]
    }
}

###

#service poy kaleis gia na deiksei kapoios endiaferon gia ena post
POST http://localhost:3000/posts/interested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlZnRlcmlzZXZhZ2VsaW5vczE5OTZAZ21haWwuY29tIiwiZGF0YSI6IjIwMjItMTEtMTJUMTI6MDU6NDMuMzcwWiIsImlhdCI6MTY2ODI1NDc0MywiZXhwIjoxNjczNDM4NzQzfQ.wxEeIB4y4AKffg7h6vEXvl3bHpejRb7vB56ZS1Oxd0E

{
    "data": {
        "email": "lefterisevagelinos1996@gmail.com",
        "postid": 1809
    }
}

###

#service pou sou epistrefei lista me posts (paginated ana 20 kai ordered me vasi imeromhnia)
POST http://localhost:3000/posts/searchposts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlZnRlcmlzZXZhZ2VsaW5vczE5OTZAZ21haWwuY29tIiwiZGF0YSI6IjIwMjItMTEtMTJUMTI6MDU6NDMuMzcwWiIsImlhdCI6MTY2ODI1NDc0MywiZXhwIjoxNjczNDM4NzQzfQ.wxEeIB4y4AKffg7h6vEXvl3bHpejRb7vB56ZS1Oxd0E

{
    "data": {
        "email": "cs11082@uniwa.gr",
        "startplace": "ασδ",
        "startcoord": "1234",
        "endplace": "δσα",
        "endcoord": "3215",
        "startdate": null,
        "enddate": null,
        "page": 1,
        "cost": 100,
        "age": null,
        "age_end": null,
        "car": null,
        "cardate": 1995,
        "gender": null,
        "withReturn": null,
        "petAllowed": null,
        "returnStartDate": null,
        "returnEndDate": null
    }
}

# {
#     "data": {
#         "email": "cs141082@uniwa.gr",
#         "startplace": "ασsδ",
#         "startcoord": "123",
#         "endplace": "δσsα",
#         "endcoord": "321",
#         "startdate": "2022-04-10",
#         "enddate": "2022-04-30",
#         "page": 1,
#         "cost": 100,
#         "age": 25,
#         "age_end": 30,
#         "car": "nissan",
#         "cardate": 1996,
#         "gender": "male",
#         "withReturn": 1,
#         "petAllowed": true,
#         "returnStartDate": "2022-11-20",
#         "returnEndDate": "2023-12-20"
#     }
# }



###

#service pou anazhtei kapoion xrhsth kai epistrefei ta stoixeia toy
POST http://localhost:3000/users/searchuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTExLTE0VDE2OjU1OjEwLjgzNFoiLCJpYXQiOjE2Njg0NDQ5MTAsImV4cCI6MTY3MzYyODkxMH0.eSGiSvs_eqz7ipo7uOH76c_JFPzCXEgOax-I9wYxvfM

{
    "data": {
        "email": "user1@gmail.com"
    }
}

###

#get reviews
POST http://localhost:3000/reviews/getReviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlZnRlcmlzZXZhZ2VsaW5vczE5OTZAZ21haWwuY29tIiwiZGF0YSI6IjIwMjItMTEtMTJUMTI6MDU6NDMuMzcwWiIsImlhdCI6MTY2ODI1NDc0MywiZXhwIjoxNjczNDM4NzQzfQ.wxEeIB4y4AKffg7h6vEXvl3bHpejRb7vB56ZS1Oxd0E

{
    "data": {
        "email": "lefterisevagelinos1996@gmail.com",
        "page": 1
    }
}

###

#Service pou eisagei ena review sth vash
POST http://localhost:3000/reviews/createreview
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlZnRlcmlzZXZhZ2VsaW5vczE5OTZAZ21haWwuY29tIiwiZGF0YSI6IjIwMjItMTEtMTJUMTI6MDU6NDMuMzcwWiIsImlhdCI6MTY2ODI1NDc0MywiZXhwIjoxNjczNDM4NzQzfQ.wxEeIB4y4AKffg7h6vEXvl3bHpejRb7vB56ZS1Oxd0E

{
    "data": {
        "emailreviewer": "user0@gmail.com",
        "email": "user1@gmail.com",
        "rating": 4,
        "text": "Πολύ καλός οδηγός, αλλά μιλάει συνέχεια"
    }
}

###

#service epistrefei lista me posts enos xrhsth
POST http://localhost:3000/getPostsUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAyVDEzOjA0OjUwLjEyOVoiLCJpYXQiOjE2NDYyMjYyOTAsImV4cCI6MTY1MTQxMDI5MH0.H1G6LpsVxZoglMmCRbcPFdinQ4Na2_-80C3N68nvDgg

{
    "data": {
        "email": "user0@gmail.com",
        "page": 1
    }
}
###

#service epistrefei post vasei id
GET http://localhost:3000/getPostPerId?postid=1785
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTA2LTIzVDA5OjU0OjU5LjI4MVoiLCJpYXQiOjE2NTU5NzgwOTksImV4cCI6MTY2MTE2MjA5OX0.F6jdTc8q-6szz0aRqzy-mtOv0reeoVUgp1neeKrSeJk

###

//Διαγρφή post μαζί με τους ενδιαφερόμενους του post
POST http://localhost:3000/deletePost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data": {
        "postid": 1565
    }
}
###

//delete of interested
POST http://localhost:3000/deleteInterested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNzMTQxMDgyQHVuaXdhLmdyIiwiZGF0YSI6IjIwMjEtMTItMTlUMTE6MDM6NTUuNTI5WiIsImlhdCI6MTYzOTkxMTgzNSwiZXhwIjoxNjQ1MDk1ODM1fQ.DlNnEmDXjJCZi_6MLaYDOUtD_3tvEFA8LcN_qLNCHn4

{
    "data": {
        "piid": 114
    }
}

###

#service poy epistrefei ta post gia ta opoia einai interested o user
POST http://localhost:3000/getInterestedPerUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTMwVDA5OjUwOjUzLjk0OFoiLCJpYXQiOjE2NDg2MzM4NTMsImV4cCI6MTY1MzgxNzg1M30.uN8E5RBBZy3fZEGioLJoUJhG7HdTRsifKBLMn4nHAyA

{
    "data": {
        "email": "user0@gmail.com"
    }
}

###

#service epistrefei lista me endiaferomenous gia ta posts enos user
POST http://localhost:3000/getInterested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTMwVDA5OjUwOjUzLjk0OFoiLCJpYXQiOjE2NDg2MzM4NTMsImV4cCI6MTY1MzgxNzg1M30.uN8E5RBBZy3fZEGioLJoUJhG7HdTRsifKBLMn4nHAyA

{
    "data": {
        "email": "user0@gmail.com",
        "page": 1
    }
}
###

#service epistrefei lista me endiaferomenous gia ena post
POST http://localhost:3000/getIntPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAyVDEzOjA0OjUwLjEyOVoiLCJpYXQiOjE2NDYyMjYyOTAsImV4cCI6MTY1MTQxMDI5MH0.H1G6LpsVxZoglMmCRbcPFdinQ4Na2_-80C3N68nvDgg

{
    "data": {
        "postid": 1785,
        "page": 1
    }
}
###

GET http://localhost:3000/autocomplete/json?input=αθη
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTE5VDE3OjE3OjIwLjA0NVoiLCJpYXQiOjE2NDUyOTEwNDAsImV4cCI6MTY1MDQ3NTA0MH0.OVf2DDS4hIeyPV3PJNbZG56iKL8-rkVtVSMzUQ3rdLI

###
GET http://localhost:3000/details/json?place_id=ChIJ8UNwBh-9oRQR3Y1mdkU1Nic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTE5VDE3OjE3OjIwLjA0NVoiLCJpYXQiOjE2NDUyOTEwNDAsImV4cCI6MTY1MDQ3NTA0MH0.OVf2DDS4hIeyPV3PJNbZG56iKL8-rkVtVSMzUQ3rdLI

###
// verify an insterested user to a post
POST http://localhost:3000/verInterested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdpYW5uaXNmcmFnb3VsaXMyMUBnbWFpbC5jb20iLCJkYXRhIjoiMjAyMi0wNi0xN1QxMzoxOTo0OC41NTVaIiwiaWF0IjoxNjU1NDcxOTg4LCJleHAiOjE2NjA2NTU5ODh9.8Qv-om9AF8ZYx6DeqTjZ71fpEykSBL859sre5dp-L1g

{
    "data": {
        "postid": 1337,
        "piid": 2222
    }
}

###

//service to notify someone that has been verified for a post that he is interested
GET http://localhost:3000/notifyMe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTA0LTIzVDEzOjAwOjQ1LjcyMFoiLCJpYXQiOjE2NTA3MTg4NDUsImV4cCI6MTY1NTkwMjg0NX0.d3mVR52EShOEtK3JMMgU3nmSQhdik0xmYmC15ZKkGoc

###
// mainEmail: se afto to email tha ginontai generated ta posts. 
// Epishs to idio email tha einai to pathitiko eimail twn reviews. (dhladh se afton tha kanoyn to review)
// To secondaryEmail einai o emailReviewer dhladh aftow poy tha kanei to review
// Gia na treksei duo fores h perissoteres to api prepei na allazei kathe fora to secondary email. (Den einai aparaithto na einai uparkto email)
// postid: dineis to id apo to post sto opoio thes na ginoun generated polloi endiaferomenoi
// postidList: lista me postid poy thes enas user na endiaferetai gia afta
POST http://localhost:3000/dbMigration
Content-Type: application/json

{
    "data": {
        "mainEmail": "lefterisevagelinos1996@gmail.com",
        "secondaryEmail": "cs1410823@uniwa.gr",
        "postid": 849,
        "postidList": [1564,1565,1566,1567,1568]
    }
}

###
POST http://localhost:3000/sendReport
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTAxVDEyOjE1OjQ4LjUwM1oiLCJpYXQiOjE2NDM3MTc3NDgsImV4cCI6MTY0ODkwMTc0OH0.3hGmuEdGzpdhiny9YD5qIAoiD8I-TPDVHcEyH1VG3FY

{
    "text": "Test report"
}
###

POST http://localhost:3000/getTerms
Content-Type: application/text/html
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAyLTAxVDEyOjE1OjQ4LjUwM1oiLCJpYXQiOjE2NDM3MTc3NDgsImV4cCI6MTY0ODkwMTc0OH0.3hGmuEdGzpdhiny9YD5qIAoiD8I-TPDVHcEyH1VG3FY
###

POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=---

###

POST http://localhost:3000/requests/createRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlZnRlcmlzZXZhZ2VsaW5vczE5OTZAZ21haWwuY29tIiwiZGF0YSI6IjIwMjItMTEtMTFUMTY6NTg6NTcuODg0WiIsImlhdCI6MTY2ODE4NTkzNywiZXhwIjoxNjczMzY5OTM3fQ.WsB22dWgg5t7BDXFu4WGhnQNSNp7cCWFYwv3yRgu6gA

{
    "data": {
        "startplace": "Volos",
        "startcoord": "1234",
        "endplace": "Athens",
        "endcoord": "3215"
    }
}

###

GET http://localhost:3000/requests/getRequests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlZnRlcmlzZXZhZ2VsaW5vczE5OTZAZ21haWwuY29tIiwiZGF0YSI6IjIwMjItMTEtMTFUMTY6NTg6NTcuODg0WiIsImlhdCI6MTY2ODE4NTkzNywiZXhwIjoxNjczMzY5OTM3fQ.WsB22dWgg5t7BDXFu4WGhnQNSNp7cCWFYwv3yRgu6gA

###
POST http://localhost:3000/requests/deleteRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlZnRlcmlzZXZhZ2VsaW5vczE5OTZAZ21haWwuY29tIiwiZGF0YSI6IjIwMjItMTEtMTFUMTY6NTg6NTcuODg0WiIsImlhdCI6MTY2ODE4NTkzNywiZXhwIjoxNjczMzY5OTM3fQ.WsB22dWgg5t7BDXFu4WGhnQNSNp7cCWFYwv3yRgu6gA

{
    "data": {
        "postSearchId": 19
    }
}

###
#service που προσθέτει/αφαιρεί ένα ποστ από τα αγαπημένα
POST http://localhost:3000/handleFavourite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTI2VDA4OjI2OjM5LjU4MFoiLCJpYXQiOjE2NDgyODMxOTksImV4cCI6MTY1MzQ2NzE5OX0.WyMRvIhi8-FmsPe04jHorrux67vS-vVybx5SU8AOHGY

{
    "data": {
        "postid": 1730
    }
}

###
#service that returns all the favourites of one user
GET http://localhost:3000/getFavourites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAyVDEzOjA0OjUwLjEyOVoiLCJpYXQiOjE2NDYyMjYyOTAsImV4cCI6MTY1MTQxMDI5MH0.H1G6LpsVxZoglMmCRbcPFdinQ4Na2_-80C3N68nvDgg

###
#service that returns all the favourites of one user
GET http://192.168.1.7:3000/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTAzLTAyVDEzOjA0OjUwLjEyOVoiLCJpYXQiOjE2NDYyMjYyOTAsImV4cCI6MTY1MTQxMDI5MH0.H1G6LpsVxZoglMmCRbcPFdinQ4Na2_-80C3N68nvDgg

###
#ALL NEW APIS 
POST http://localhost:3000/posts/createPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTEwLTI2VDE0OjU3OjI4LjI5MVoiLCJpYXQiOjE2NjY3OTYyNDgsImV4cCI6MTY3MTk4MDI0OH0.aqDYU4dG3OfcVJ39eiLxiAAqU2y8V8-A_1dLpfDq2EA

{
    "data": {
        "email": "user0@gmail.com",
        "date": "2021-10-05",
        "startplace": "ασδ",
        "startcoord": "1234",
        "endplace": "δσα",
        "endcoord": "3215",
        "numseats": 2,
        "startdate": "2022-04-22",
        "enddate": null,
        "returnStartDate": null,
        "returnEndDate": null,
        "withReturn": false,
        "costperseat": 40,
        "comment": "Αν δεν επικοινωνήσω σημαίνει ότι δεν υπάρχουν θέσεις.",
        "petAllowed": true,
        "isFavourite": false,
        "moreplaces": [
            {
                    "place": "lamia",
                    "placecoords": "3211"
            },
            {
                    "place": "lamia",
                    "placecoords": "3211"
            }
        ]
    }
}

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "data":{
        "email": "lollololol@opa.com",
        "password": "12345",
        "mobile": "6975620785",
        "fullname": "lefos evan",
        "gender": "male",
        "car": null,
        "cardate": null,
        "age": "26",
        "photo": "/9j/4AAQSkZJRgABAQEAeAB4AAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAYACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKKKACiiigAooooAKKKKACiiigAooooA//Z"
    }
}

###
POST http://localhost:3000/users/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIwQGdtYWlsLmNvbSIsImRhdGEiOiIyMDIyLTEwLTI2VDE0OjU3OjI4LjI5MVoiLCJpYXQiOjE2NjY3OTYyNDgsImV4cCI6MTY3MTk4MDI0OH0.aqDYU4dG3OfcVJ39eiLxiAAqU2y8V8-A_1dLpfDq2EA

{
    "data": {
        "fullname": "George1",
        "mobile": "6975620785",
        "age": 25,
        "facebook": null,
        "instagram": null,
        "car": "nissan",
        "cardate": "1996",
        "photo": "/9j/4AAQSkZJRgABAQEAeAB4AAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAYACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKKKACiiigAooooAKKKKACiiigAooooA//Z"
    }
}